apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sd5976-msa
  namespace: argocd
  annotations:
    # ArgoCD Image Updater configuration - monitors ECR for new images
    argocd-image-updater.argoproj.io/image-list: |
      backend=177629262279.dkr.ecr.ap-southeast-1.amazonaws.com//sd5976-backend,
      frontend=177629262279.dkr.ecr.ap-southeast-1.amazonaws.com//sd5976-frontend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/tri-dominh/sd5976_devops_cicd_deployment.git
    targetRevision: main
    path: argocd-deployment

  destination:
    server: https://kubernetes.default.svc
    namespace: sd5976-msa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
